### ISSUE TITLE
How do run for more number number of iterations?

### ISSUE THREAD

**Issue by keerthanpg** [skjb/pysc2-tutorial#3]
I cloned and ran step5 smart agent and it always terminates at 2500 steps. 

![image](https://user-images.githubusercontent.com/10848943/32425766-8331222c-c283-11e7-9a36-e108f7f8d033.png)

Also, the rewards are 0 for as far as I can see. How do we check the history?

**Comment by skjb** [comment]
@keerthanpg make sure you use `--max_agent_steps 0` as a command line argument when running the agent

The reward will be 0 except for steps immediately after an enemy unit or building is killed

**Comment by nanxintin** [comment]
Hi, I followed your method to add "--max_agent_steps 0" as a command line argument , but the agent still ended after 2500 steps.  I also changed the max_agent_steps in the pysc2/bin/agent.py, it didn't work too.
Can you give me some suggestions? Thanks.
